version: '3.8'
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2381"
      ETCDCTL_API: "3"
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
    volumes:
      - juno_data/etcd:/etcd

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - juno_data/mysql/data:/var/lib/mysql
      - juno_data/mysql/conf.d:/etc/mysql/conf.d

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - juno_data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - etcd
    restart: on-failure

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - juno_data/grafana/:/etc/grafana/conf/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: on-failure
  
volumes:
  juno_data:
    driver: local